// Azure Managed Grafana in front of the Claude gateway logs.
//
// COST WARNING: this is the only billable resource in this repo, and it recurs.
// East US retail at time of writing: $0.0342/hour node (~$25/month) + $6/user/month.
//
// An 'Essential' SKU appears in the Azure retail price list at $6/user/month with no
// node charge, but ARM REJECTS IT - "The Grafana Workspace sku name 'Essential' is not
// a supported value. Supported sku values are: Standard" - on every api-version from
// 2024-10-01 through 2026-09-01, and in eastus, westus2, centralus and westeurope.
// Treat it as unavailable unless your subscription is allowlisted. Budget for Standard.
//
//   az provider register --namespace Microsoft.Dashboard        # NOT registered by default
//   az deployment group create -g <rg> -f 11-grafana.bicep \
//      -p grafanaName=<name> logAnalyticsWorkspaceId=<workspace resource id> \
//         adminPrincipalId=$(az ad signed-in-user show --query id -o tsv)
//
// The dashboard itself is NOT deployable from here. Azure Managed Grafana has no ARM
// path for dashboards - import 12-claude-usage-grafana-dashboard.json afterwards with
// 13-import-grafana-dashboard.sh.

@description('Grafana instance name. 2-30 chars, must start with a letter.')
@minLength(2)
@maxLength(30)
param grafanaName string

@description('Resource ID of the Log Analytics workspace holding GatewayLlmLogs and GatewayLogs.')
param logAnalyticsWorkspaceId string

@description('Object ID of the principal who should administer Grafana. Without this you can deploy the instance but not open it.')
param adminPrincipalId string

@description('Standard is the only SKU ARM accepts today; see the note above about Essential.')
@allowed([ 'Standard' ])
param skuName string = 'Standard'

param location string = resourceGroup().location

resource grafana 'Microsoft.Dashboard/grafana@2024-10-01' = {
  name: grafanaName
  location: location
  sku: {
    name: skuName
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    // No API keys: the instance authenticates to Azure with its managed identity, and
    // humans authenticate with Entra. Same principle as the gateway itself.
    apiKey: 'Disabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    publicNetworkAccess: 'Enabled'
    zoneRedundancy: 'Disabled'
  }
}

// Monitoring Reader on the workspace, via a module: the workspace is typically in a
// different resource group from Grafana, and Bicep rejects a cross-resource-group role
// assignment with BCP139. The module targets the workspace's own resource group, parsed
// out of the resource ID so the caller still passes only one value.
module workspaceRbac './11a-grafana-workspace-rbac.bicep' = {
  name: 'grafana-monitoring-reader'
  scope: resourceGroup(split(logAnalyticsWorkspaceId, '/')[4])
  params: {
    workspaceName: last(split(logAnalyticsWorkspaceId, '/'))
    grafanaPrincipalId: grafana.identity.principalId
    grafanaResourceId: grafana.id
  }
}

// Grafana Admin — Azure RBAC on the Grafana resource maps to a role INSIDE Grafana.
// Owner and Contributor on the resource do NOT grant sign-in to the Grafana UI.
var grafanaAdmin = '22926164-76b3-42b3-bc55-97df8dab3e41'

resource adminAccess 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: grafana
  name: guid(grafana.id, adminPrincipalId, grafanaAdmin)
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', grafanaAdmin)
    principalId: adminPrincipalId
  }
}

output grafanaEndpoint string = grafana.properties.endpoint
output grafanaName string = grafana.name
output grafanaPrincipalId string = grafana.identity.principalId
