// Azure Managed Grafana in front of the Claude gateway logs.
//
// COST WARNING: this is the only billable resource in this repo, and it recurs.
// East US retail at time of writing:
//   Essential  $6/user/month, no node charge          <- default here
//   Standard   $0.0342/hour node (~$25/month) + $6/user/month
// Essential has no SLA and a reduced feature set. Choose Standard if you need
// the SLA, Grafana-native alerting at scale, or additional plugins.
//
//   az provider register --namespace Microsoft.Dashboard        # NOT registered by default
//   az deployment group create -g <rg> -f 11-grafana.bicep \
//      -p grafanaName=<name> logAnalyticsWorkspaceId=<workspace resource id> \
//         adminPrincipalId=$(az ad signed-in-user show --query id -o tsv)
//
// The dashboard itself is NOT deployable from here. Azure Managed Grafana has no ARM
// path for dashboards - import 12-claude-usage-grafana-dashboard.json afterwards with
// 13-import-grafana-dashboard.sh.

@description('Grafana instance name. 2-30 chars, must start with a letter.')
@minLength(2)
@maxLength(30)
param grafanaName string

@description('Resource ID of the Log Analytics workspace holding GatewayLlmLogs and GatewayLogs.')
param logAnalyticsWorkspaceId string

@description('Object ID of the principal who should administer Grafana. Without this you can deploy the instance but not open it.')
param adminPrincipalId string

@description('Essential is per-user only. Standard adds a node charge and an SLA.')
@allowed([ 'Essential', 'Standard' ])
param skuName string = 'Essential'

param location string = resourceGroup().location

resource grafana 'Microsoft.Dashboard/grafana@2024-10-01' = {
  name: grafanaName
  location: location
  sku: {
    name: skuName
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    // No API keys: the instance authenticates to Azure with its managed identity, and
    // humans authenticate with Entra. Same principle as the gateway itself.
    apiKey: 'Disabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    publicNetworkAccess: 'Enabled'
    zoneRedundancy: 'Disabled'
  }
}

// Existing-resource references so the role assignments can be scoped correctly.
resource workspace 'Microsoft.OperationalInsights/workspaces@2022-10-01' existing = {
  name: last(split(logAnalyticsWorkspaceId, '/'))
}

// Monitoring Reader — what lets Grafana's managed identity actually run KQL against the
// workspace. Omit it and the instance deploys fine, then every panel returns a
// permissions error that reads like a broken datasource.
var monitoringReader = '43d0d8ad-25c7-4714-9337-8ba259a9fe05'

resource grafanaReadsLogs 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: workspace
  name: guid(workspace.id, grafana.id, monitoringReader)
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', monitoringReader)
    principalId: grafana.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

// Grafana Admin — Azure RBAC on the Grafana resource maps to a role INSIDE Grafana.
// Owner and Contributor on the resource do NOT grant sign-in to the Grafana UI.
var grafanaAdmin = '22926164-76b3-42b3-bc55-97df8dab3e41'

resource adminAccess 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: grafana
  name: guid(grafana.id, adminPrincipalId, grafanaAdmin)
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', grafanaAdmin)
    principalId: adminPrincipalId
  }
}

output grafanaEndpoint string = grafana.properties.endpoint
output grafanaName string = grafana.name
output grafanaPrincipalId string = grafana.identity.principalId
